#!/usr/bin/env bash
set -euo pipefail

# One-click export:
# 1) nbconvert notebook -> html
# 2) patch MathJax to v3 config so inline math renders reliably
#
# Usage:
#   ./export_html.sh
#   ./export_html.sh brachistochrone.ipynb brachistochrone.html

NOTEBOOK="${1:-brachistochrone.ipynb}"
OUTPUT_HTML="${2:-brachistochrone.html}"

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_JUPYTER="$ROOT_DIR/.venv/bin/jupyter"

if [[ ! -x "$VENV_JUPYTER" ]]; then
  echo "Error: $VENV_JUPYTER not found. Create/activate .venv first." >&2
  exit 1
fi

TMP_JUPYTER_CFG="$ROOT_DIR/.jupyter"
mkdir -p "$TMP_JUPYTER_CFG"

echo "[1/2] Exporting $NOTEBOOK -> $OUTPUT_HTML ..."
JUPYTER_CONFIG_DIR="$TMP_JUPYTER_CFG" \
  "$VENV_JUPYTER" nbconvert \
    --to html \
    --embed-images \
    --HTMLExporter.mathjax_url='https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js' \
    "$NOTEBOOK" \
    --output "$OUTPUT_HTML"

echo "[2/2] Patching MathJax config for inline math ..."
python3 - "$OUTPUT_HTML" <<'PY'
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")

# Remove legacy v2 config block generated by nbconvert, if present.
text = re.sub(
    r'<!-- Load mathjax -->\s*'
    r'<script[^>]*mathjax@3/es5/tex-mml-chtml\.js[^>]*>\s*</script>\s*'
    r'<!-- MathJax configuration -->\s*'
    r'<script type="text/x-mathjax-config">.*?</script>\s*'
    r'<!-- End of mathjax configuration -->',
    '',
    text,
    flags=re.S | re.I,
)

# Remove our own previously injected block (idempotent reruns).
text = re.sub(
    r'<!-- MathJax configuration -->\s*'
    r'<script>\s*window\.MathJax\s*=.*?</script>\s*'
    r'<!-- Load MathJax -->\s*'
    r'<script[^>]*mathjax@3/es5/tex-mml-chtml\.js[^>]*></script>\s*'
    r'<!-- End of MathJax configuration -->\s*',
    '',
    text,
    flags=re.S | re.I,
)

mathjax_block = """<!-- MathJax configuration -->
<script>
window.MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\\\(', '\\\\)']],
    displayMath: [['$$', '$$'], ['\\\\[', '\\\\]']],
    processEscapes: true
  },
  options: {
    skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
  }
};
</script>
<!-- Load MathJax -->
<script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<!-- End of MathJax configuration -->
"""

# Insert before the first module script near the end of <head>.
module_script_idx = text.find('<script type="module">')
if module_script_idx != -1:
    text = text[:module_script_idx] + mathjax_block + text[module_script_idx:]
else:
    # Fallback: place before </head>
    text = text.replace("</head>", mathjax_block + "\n</head>", 1)

path.write_text(text, encoding="utf-8")
print(f"Patched MathJax in {path}")
PY

echo "Done: $OUTPUT_HTML"
